# Generated by Django 2.0.2 on 2018-10-04 19:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terms', '0002_term_usersfollowing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='usersFollowing',
            field=models.ManyToManyField(blank=True, related_name='followingTerms', to=settings.AUTH_USER_MODEL),
        ),
    ]
